"$schema" = 'https://starship.rs/config-schema.json'

format = """
$cmd_duration\
[](red)\
$os\
[](bg:comment fg:red)\
$username\
[](bg:purple fg:comment)\
$directory\
[](bg:orange fg:purple)\
$git_branch\
$git_status\
[](bg:cyan fg:orange)\
$c\
$rust\
$golang\
$nodejs\
$bun\
$php\
$java\
$kotlin\
$haskell\
$python\
$conda\
[](bg:pink fg:cyan)\
$time\
[ ](fg:pink)"""

palette = 'dracula'
add_newline = false

[os]
disabled = false
style = "bg:red fg:foreground"
format = '[ $symbol ]($style)'

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:comment fg:foreground"
style_root = "bg:comment fg:foreground"
format = '[$user ]($style)'

[directory]
style = "bg:purple fg:foreground"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
home_symbol = "󰀵"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:orange"
format = '[[ $symbol $branch ](fg:foreground bg:orange)]($style)'

[git_status]
style = "bg:orange"
format = '[[($all_status$ahead_behind )](fg:foreground bg:orange)]($style)'

[nodejs]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:foreground bg:cyan)]($style)'

[bun]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:foreground bg:cyan)]($style)'

[c]
symbol = " "
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:foreground bg:cyan)]($style)'

[rust]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:foreground bg:cyan)]($style)'

[golang]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:foreground bg:cyan)]($style)'

[php]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:foreground bg:cyan)]($style)'

[java]
symbol = " "
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:foreground bg:cyan)]($style)'

[kotlin]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:foreground bg:cyan)]($style)'

[haskell]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:foreground bg:cyan)]($style)'

[python]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:foreground bg:cyan)]($style)'

[conda]
symbol = "  "
style = "fg:foreground bg:cyan"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:pink"
format = '[[ $time ](fg:foreground bg:pink)]($style)'

[line_break]
disabled = true

[character]
disabled = true

[cmd_duration]
show_milliseconds = true
format = " $duration\n"
style = "bold fg:comment"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[palettes.dracula]
background = "#282A36"
foreground = "#F8F8F2"
pink = "#ff79c6"
red = "#ff5555"
yellow = "#f1fa8c"
green = "#50fa7b"
cyan = "#8be9fd"
purple = "#bd93f9"
orange = "#ffb86c"
comment = "#6272a4"
